# Generated by Django 3.1.7 on 2021-03-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='clue_map',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
