# Generated by Django 3.1.7 on 2021-03-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0002_clue_clue_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='clue_answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
