# Generated by Django 3.1.7 on 2021-03-25 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0003_clue_clue_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='', max_length=100)),
                ('jenga_score', models.IntegerField()),
                ('volleyball_score', models.IntegerField()),
            ],
        ),
    ]
